#!/usr/bin/env bash

window_name=$(basename $1)
pane=$(basename $2)
session_name=$(tmux display-message -p "#S")
target=$session_name:$window_name

if ! tmux has-session -t $target 2> /dev/null; then
    tmux neww -dn $window_name
fi

if ! tmux has-session -t $target.$pane 2> /dev/null; then
    tmux select-window -t $window_name
    tmux splitw -h
    tmux previous-window
fi

shift
shift

tmux send-keys -t $target.$pane "$*"
