#!/usr/bin/env bash

window_name="Yazi"

if [ "$1" != "" ]; then
    root_path=$1
else
    root_path=""
fi

if [ "$root_path" = "i0i" ]; then
    root_path="/home/i0i/"
fi

tmux neww -n $window_name "yazi $root_path"
