#!/usr/bin/env bash

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

create_directory() {
    local dir_path=$1
    if [ ! -d "$dir_path" ]; then
        mkdir -p "$dir_path"
    fi
}

install_git() {
    local repo=$1
    local path=$2
    if [ -d "$path" ]; then
        echo "Repository exists at $repo. Updating..."
        cd "$path"
        git pull
        echo "$repo was updated."
    else
        echo "Cloning $repo to $path"
        git clone https://github.com/$repo --depth=1 "$path"
        echo "$repo was installed."
    fi
}


create_directory $HOME/apps

off_packages="clang fish bat fd fzf btop ghostty qbittorrent telegram-desktop yazi tmux spotifyd openssh"
aur_packages="visual-studio-code-bin zed-preview-bin zen-browser-bin windserf-next spotify dropbox-cli" # balena-cli-bin

sudo pacman -Syu
sudo pacman -S --needed git curl base-devel clang cmake unzip ninja alsa-lib stow go

sudo pacman -S --needed $off_packages

yay -S --needed $aur_packages

install_git "neovim/neovim" "$HOME/apps/neovim"
cd $HOME/apps/neovim && make CMAKE_BUILD_TYPE=Release && sudo make install

install_git "i0i-i0i/init.lua" "$HOME/.config/nvim"
