#!/usr/bin/env bash

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

create_directory() {
    local dir_path=$1
    if [ ! -d "$dir_path" ]; then
        mkdir -p "$dir_path"
    fi
}

install_git() {
    local repo=$1
    local path=$2
    if [ -d "$path" ]; then
        echo "Repository exists at $repo. Updating..."
        cd "$path"
        git pull
        echo "$repo was updated."
    else
        echo "Cloning $repo to $path"
        git clone https://github.com/$repo --depth=1 "$path"
        echo "$repo was installed."
    fi
}

create_directory $HOME/apps

off_packages="clang bat fd fzf btop yazi tmux spotifyd openssh auto-cpufreq zathura zen-browser"
aur_packages="visual-studio-code-bin windsurf spotify dropbox-cli balena-cli-bin"

case "$1" in
    wayland) packs="wlr-randr wlroots foot grim wmenu waybar" ;;
    x11) packs="xorg-server xorg-xinit xorg-xrandr" ;;
    *)
        echo "Ivalid arg: $1"
        echo "[ wayland | x11 ] are available"
        exit 1
        ;;
esac

amd_drivers="mesa-vdpau vulkan-icd-loader vulkan-radeon mesa amd-ucode"
nvidia_drivers="nvidia nvidia-utils nvidia-dkms"
intel_drivers="intel-media-driver vulkan-intel mesa intel-ucode"

case "$2" in
    amd) sudo pacman -S --needed $amd_drivers ;;
    intel) sudo pacman -S --needed $intel_drivers ;;
    nvidia) sudo pacman -S --needed $nvidia_drivers ;;
    amd_nvidia) sudo pacman -S --needed $amd_drivers $nvidia_drivers ;;
    intel_nvidia) sudo pacman -S --needed $intel_drivers $nvidia_drivers ;;
    all) sudo pacman -S --needed $intel_drivers $amd_dirvers $nvidia_drivers ;;
    *)
        echo "Ivalid arg: $2"
        echo "[ amd | nvidia | intel ] are available"
        exit 1
        ;;
esac

sudo pacman -Syu
sudo pacman -S --needed git curl wget base-devel clang cmake unzip ninja alsa-lib stow go $off_packages $packs

sleep 1

paru -S --needed $aur_packages

install_git "neovim/neovim" "$HOME/apps/neovim"
cd $HOME/apps/neovim && make CMAKE_BUILD_TYPE=Release && sudo make install

install_git "i0i-i0i/init.lua" "$HOME/.config/nvim"
