#!/usr/bin/env bash

fimg() {
    cmd="find ~/.dotfiles/walls -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' -o -iname '*.webp' \)"

  preview_cmd="img2sixel -w 800 -q low {} 2>/dev/null || echo 'Preview failed'"

  eval "$cmd" | fzf \
    --preview="$preview_cmd" \
    --preview-window="right:50%"
}

IMG=$(fimg)

if [ -z "$IMG" ]; then
    exit 0
fi

killall wbg &>/dev/null
wbg "$IMG" &>/dev/null &
sed -i \
    -E "s|^(wbg) /home/nnofly/.dotfiles/walls/[^/]+\.jpg( &.*)$|\1 $IMG\2|" \
  ~/.dotfiles/scripts/start

disown -a
