#!/usr/bin/env bash

IMG=$(imv -r ~/.dotfiles/walls/)

if [ -z "$IMG" ]; then
    exit 0
fi

killall wbg &>/dev/null
wbg "$IMG" &>/dev/null &
sed -i \
  -E "s|^(.*wbg) ~/.dotfiles/walls/[^/]+\.jpg( &.*)$|\1 $IMG\2|" \
  ~/start

disown -a
