#!/usr/bin/env bash

dwl &
sleep 1
wlsunset -S 4:30 -s 23:00 -t 4000:6500 &
waybar &
wl-paste --watch cliphist store &
alacritty --daemon &
waypaper --restore &
emacs --daemon=doom &

if [ -f "$HOME/.config/systemd/user/swayidle.service" ]; then
    systemctl --user start swayidle.service
fi
