#!/usr/bin/env bash

set -euo pipefail

check_command() {
    command_exists() {
        command -v "$1" >/dev/null 2>&1
    }

    msg="'$1' is not installed!"
    if ! command_exists "$1"; then
        echo "$msg"
        notify-send -a TimeSpent "$msg" -u critical -t 3000
        exit 1
    fi
}

check_command timew
check_command fzf

CATEGORIES=(
    "STOP"
    "WORK"
    "LEARNING"
    "CUSTOMIZING"
    "WASTED"
)

timespent_get() {
    current_tracking=$(timew get dom.active)

    if [ -n "$current_tracking" ] && [ "$current_tracking" != "0" ]; then
        category=$(timew get dom.active.tags)
        time_output=$(timew day "$category" 2>/dev/null | grep Tracked | awk '{print $2}')
        if [ -n "$time_output" ]; then
            IFS=: read hours minutes _ <<< "$time_output"
            if ((hours == 0)); then
                echo "${minutes}m $category"
            else
                echo "${hours}h ${minutes}m $category"
            fi
        else
            echo "Tracking: $category"
        fi
    else
        echo ""
    fi
}

timespent_set() {
    selected=$(printf "%s\n" "${CATEGORIES[@]}" | fzf --prompt="Category:")

    if [ -z "$selected" ]; then
        exit 0
    fi

    if [[ "$selected" == "STOP" ]]; then
        timew stop >/dev/null 2>&1
        tmux set -g status-right ""
    else
        timew start "$selected" >/dev/null 2>&1
        tmux set -g status-right "#(echo \"$(timespent_get)\")"
        tmux set -g status-interval 60
    fi

    urls=("www.youtube.com")
    if [[ "$selected" == "WORK" ]]; then
        for url in $urls; do
            echo "::1 $url" >> /etc/hosts
        done
    else
        for url in $urls; do
            sudo sed -i.auto_bak -E "/^(::1|127\\.0\\.0\\.1)[[:space:]]+$url/d" /etc/hosts
        done
    fi
}

case "$1" in
    "get") timespent_get ;;
    "set") timespent_set ;;
esac
