#!/usr/bin/env bash

set -euo pipefail

check_command() {
    command_exists() {
        command -v "$1" >/dev/null 2>&1
    }

    msg="'$1' is not installed!"
    if ! command_exists "$1"; then
        echo "$msg"
        notify-send -a TimeSpent "$msg" -u critical -t 3000
        exit 1
    fi
}

check_command timew
check_command fzf

CATEGORIES=(
    "STOP"
    "WORK"
    "CUSTOMIZING"
    "WASTED"
)

if [ -z "$(tmux show-environment -g TIMESPENT_INITIALIZED 2>/dev/null)" ]; then
    DEFAULT_TMUX_STATUS_RIGHT=$(tmux show-option -gv status-right 2>/dev/null || echo "")
    tmux set-environment -g TIMESPENT_INITIALIZED 1
    tmux set-environment -g DEFAULT_TMUX_STATUS_RIGHT "$DEFAULT_TMUX_STATUS_RIGHT"
else
    DEFAULT_TMUX_STATUS_RIGHT=$(tmux show-environment -g DEFAULT_TMUX_STATUS_RIGHT 2>/dev/null | cut -d= -f2-)
fi

help() {
    cat <<EOF
Usage:
    timespent get - get time spent for the current category
    timespent set - set the current category (select from [${CATEGORIES[@]}] with fzf)
EOF
}

modify_hosts() {
    local action="$1"
    local url="$2"

    case "$action" in
        "block")
            echo "::1 $url" | sudo tee -a /etc/hosts > /dev/null
            echo "127.0.0.1 $url" | sudo tee -a /etc/hosts > /dev/null
            ;;
        "unblock")
            sudo sed -i.auto_bak -E "/^(::1|127\\.0\\.0\\.1)[[:space:]]+$url/d" /etc/hosts
            ;;
    esac
}

timespent_get() {
    current_tracking=$(timew get dom.active)

    if [ -n "$current_tracking" ] && [ "$current_tracking" != "0" ]; then
        category=$(timew get dom.active.tags)
        time_output=$(timew day "$category" 2>/dev/null | grep Tracked | awk '{print $2}')
        if [ -n "$time_output" ]; then
            IFS=: read hours minutes _ <<< "$time_output"
            if ((hours == 0)); then
                echo "${minutes}m $category"
            else
                echo "${hours}h ${minutes}m $category"
            fi
        else
            echo "Tracking: $category"
        fi
    else
        echo ""
    fi
}

timespent_set() {
    if [[ -z "${2:-}" ]]; then
        category=$(printf "%s\n" "${CATEGORIES[@]}" | fzf --prompt="Category:")
    elif [[ "${CATEGORIES[*]}" == *"$2"* ]]; then
        category="$2"
    else
        echo "Category '$2' is not valid!"
        echo "Use one of the following categories: ${CATEGORIES[*]}"
        exit 1
    fi

    if [[ "$category" == "STOP" ]]; then
        timew stop >/dev/null 2>&1
        tmux set -g status-right "$DEFAULT_TMUX_STATUS_RIGHT"
    else
        timew start "$category" >/dev/null 2>&1
        tmux set -g status-right "#(echo \"$(timespent_get)\") | $DEFAULT_TMUX_STATUS_RIGHT"
        tmux set -g status-interval 60
    fi

    urls=("www.youtube.com")
    if [[ "$category" == "WORK" ]]; then
        for url in $urls; do
            modify_hosts "block" "$url"
        done
    else
        for url in $urls; do
            modify_hosts "unblock" "$url"
        done
    fi
}

if [[ -z "${1:-}" ]]; then
    help
    exit 1
fi

case "$1" in
    "get") timespent_get ;;
    "set") timespent_set "$@" ;;
    *) echo "Invalid command!"; help; exit 1 ;;
esac
