#!/usr/bin/env bash

set -eu

terminal="footclient"

selected=$(find ~/.dotfiles ~/.config ~/code/* ~/Sync  -mindepth 0 -maxdepth 1 -type d | rofi -dmenu -i -p 'Projects:')
[ -n "$selected" ] || exit 0

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

pkill -x $terminal 2>/dev/null || true
sleep 0.1

exec $terminal -e tmux new-session -As "$selected_name" -c "$selected"
