#!/bin/bash

current_direction=$1

window_id=$(hyprctl clients -j | jq -r '.[] | select(.class == "kitty-sidebar") | .address')

if [[ -n "$window_id" ]]; then
    hyprctl dispatch closewindow address:$window_id
else
    kitty --class=kitty-sidebar -e bash -c "trans -s ${current_direction:0:2} -t ${current_direction:3:2}" &

    sleep 0.5

    screen_width=$(hyprctl monitors -j | jq '.[0].width')
    screen_height=$(hyprctl monitors -j | jq '.[0].height')

    sidebar_width=400
    sidebar_height=$screen_height
    sidebar_x=$((screen_width - sidebar_width))
    sidebar_y=0

    hyprctl dispatch movewindowpixel exact $sidebar_x,$sidebar_y,address:$(hyprctl clients -j | jq -r '.[] | select(.class == "kitty-sidebar") | .address')
    hyprctl dispatch resizewindowpixel exact $sidebar_width,$sidebar_height,address:$(hyprctl clients -j | jq -r '.[] | select(.class == "kitty-sidebar") | .address')
fi

