#!/usr/bin/env bash

if [ -f /etc/environment ]; then
    source /etc/environment
else
    echo "Error: /etc/environment not found" >&2
    exit 1
fi

IP=$(curl https://ifconfig.me 2> /dev/null)

if [ -z "$IP" ]; then
    echo "Error: IP address not found" >&2
    exit 1
fi

if [ "$IP" != "$SERVER_IP" ]; then
    IP="$IP" vpnup
else
    vpndown
fi

